#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

[ -f ~/.Xdefaults ] && xrdb -merge ~/.Xdefaults

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set default cursor to the left pointer one, even on empty windows
# Requires `xsetroot`
# xsetroot -cursor_name left_ptr

# Start blue light filter
redshift &

# Enable multiple keyboard layouts and switching
setxkbmap -layout gb,ua,il,ru -option grp:shifts_toggle

# Set Caps Lock to emulate Ctrl key; mainly intended for kitty, although I don't use the button much anyway
setxkbmap -option caps:ctrl_modifier

# Start window manager
exec dbus-launch --sh-syntax --exit-with-session bspwm >> /tmp/bspwm.log 2>&1
