# Load the plugins with plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "robertmeta/plug.kak" noload config %{
	set-option plug_depth_sort true
}

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}
plug "alexherbo2/prelude.kak"
plug "alexherbo2/connect.kak" do %{
    make install
}
plug "alexherbo2/explore.kak"

# Colorscheme
colorscheme solarized-light

# Tabstop and indentwidth
set-option global tabstop 4
set-option global indentwidth 4

# Soft wrapping
add-highlighter global/ wrap -indent -word -width 80

# Line numbers
add-highlighter global/ number-lines -relative -min-digits '3' -separator ' '

# Diary Entries
define-command diary-new %{ edit %sh{ echo "$HOME/notes/diary/$(date +%F).md" } }
define-command diary-previous %{ edit %sh{ echo "$(find $HOME/notes/diary -maxdepth 1 -type f | sed -n 'x;$p')" } }	# this sed magic was picked up from https://stackoverflow.com/a/7671768; don't really understand it :/
