# Remove the newline before each prompt
add_newline = false

[cmd_duration]
show_milliseconds = true
min_time_to_notify = 10_000

[directory]
truncation_length = 6

[hostname]
ssh_only = false

[sudo]
disabled = false
