# Remove the newline before each prompt
add_newline = false

[battery]
disabled = true

[command_timeout]
show_milliseconds = true		# Show command's time execution

[hostname]
ssh_only = false

[username]
show_always = true
