#!/bin/bash

# AUTOSTART

## Hotkey Daemon
sxhkd &

## Panel
$XDG_CONFIG_HOME/polybar/launch.sh

# COLORSCHEME

### Set the border colors.
bspc config normal_border_color 	"#e4e4e4"
bspc config active_border_color 	"#5f8700"
bspc config focused_border_color 	"#52676f"
bspc config presel_feedback_color 	"#e4e4e4"

# WINDOW LAYOUT

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle		 true

## APPLICATION RULES
bspc rule -a Zathura state=tiled
bspc rule -a mpv Media Player desktop='^6' follow=on
bspc rule -a Emacs desktop='^7' state=tiled follow=on
bspc rule -a qBittorrent desktop='^8' follow=on				# broken :(
bspc rule -a KeePassXC desktop='^9' follow=on
bspc rule -a Firefox desktop='^10' follow=on
