#!/bin/bash

# Colorscheme ──────────────────────────────────────────────────────────────────
## Set the border colors.
bspc config normal_border_color 	"#e4e4e4"
bspc config active_border_color 	"#5f8700"
bspc config focused_border_color 	"#52676f"
bspc config presel_feedback_color 	"#e4e4e4"

# Windows ──────────────────────────────────────────────────────────────────────
## Workspace names
bspc monitor -d I II III IV V VI VII VIII IX X

## Layout
bspc config border_width         3
bspc config window_gap           5
bspc config split_ratio          0.5

## Monocle mode
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle		   true

# Rules ────────────────────────────────────────────────────────────────────────
bspc rule -a Zathura								state=tiled
bspc rule -a Anki										state=tiled	 desktop='^5'  follow=on
bspc rule -a mpv Media Player										 desktop='^6'  follow=on
bspc rule -a GIMP										state=tiled	 desktop='^6'  follow=on
bspc rule -a Picard									state=tiled	 desktop='^6'  follow=on
bspc rule -a qBittorrent												 desktop='^7'  follow=on
bspc rule -a Nicotine						 								 desktop='^7'  follow=on
bspc rule -a Element						 								 desktop='^8'  follow=on
bspc rule -a TelegramDesktop				 						 desktop='^8'  follow=on
bspc rule -a KeePassXC						 							 desktop='^9'  follow=on
bspc rule -a Firefox						 								 desktop='^10' follow=on

# Autostart ────────────────────────────────────────────────────────────────────
## Hotkey Daemon
pgrep -x sxhkd > /dev/null || sxhkd &

## Notification Manager
pgrep -x dunst > /dev/null || dunst &

## Panel
"$XDG_CONFIG_HOME"/polybar/launch.sh

## Calendar & Startup Terminal
pgrep -x kitty > /dev/null || kitty calcurse
pgrep -x kitty > /dev/null || kitty
